{
  parserClass="net.exoego.intellij.smashtest.parser.SmashtestParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Smashtest"
  psiImplClassSuffix="Impl"
  psiPackage="net.exoego.intellij.smashtest.psi"
  psiImplPackage="net.exoego.intellij.smashtest.impl"

  elementTypeHolderClass="net.exoego.intellij.smashtest.psi.SmashtestTypes"
  elementTypeClass="net.exoego.intellij.smashtest.psi.SmashtestElementType"
  tokenTypeClass="net.exoego.intellij.smashtest.psi.SmashtestTokenType"
}

smashtestFile ::= pattern_*

private pattern_ ::= (comment|step)

step ::= text+ comment?

//private escapeCharOrVariables_ ::= (escapeChar|variable)
//singleQuote ::= "'" escapeCharOrVariables_* "'"
//doubleQuote ::= "\"" escapeCharOrVariables_* "\""

//private escapeCharOrVariablesOrBracketedString_ ::= (escapeChar|variable|bracketedString)
//bracketedString ::= "[" escapeCharOrVariablesOrBracketedString_* "]"


variable ::= (localVariable|globalVariable)

//codeBlock ::= "{" SOURCE_JS? "}"

//debugModifier ::= ("~"|"~~")
//debug ::= (debugModifier step|step debugModifier)
//
//textualModifier ::= "-"
//textualStep ::= (textualModifier step|step textualModifier)
